# docker-compose --log-level INFO up --build portable-mysql57
# docker-compose --log-level INFO up

version: '3'
services:
  portable-mysql57:
    stdin_open: true
    tty: true
    image: terwer/mysql57:5.7.38
    container_name: portable-mysql57
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - "3306:3306"
    environment:
     - "TZ=Asia/Shanghai"
     - "MYSQL_ROOT_PASSWORD=123456"
     - "MYSQL_ROOT_HOST=%"
     - "MYSQL_DATABASE=test"
     - "MYSQL_USER=terwer"
     - "MYSQL_PASSWORD=123456"
    volumes:
     - ./data:/var/lib/mysql
     - ./init:/docker-entrypoint-initdb.d/
     - ./sql:/opt/
     - ./mylog:/mylog/
    restart: "no"
    networks:
      - local-dev

networks:
  local-dev:
    external: true