# docker-compose up --build
# docker-compose up

version: '3'
services:
  portable-mysql57:
    stdin_open: true
    tty: true
    privileged: true
    image: terwer/mysql57:5.7.38
    container_name: portable-mysql57
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - "3306:3306"
    environment:
     - "TZ=Asia/Shanghai"
     - "MYSQL_ROOT_PASSWORD=123456"
     - "MYSQL_ROOT_HOST=%"
     - "MYSQL_DATABASE=test"
     - "MYSQL_USER=terwer"
     - "MYSQL_PASSWORD=123456"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ./sql:/opt/
    restart: "no"
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 3