# docker-compose --log-level INFO up --build docker-centos-vnc
# docker-compose --log-level INFO up

version: '3'
services:
  portable-mysql57-centos7:
    stdin_open: true
    tty: true
    image: terwer/mysql57-centos7:5.7.38
    container_name: portable-mysql57-centos7
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - "3306:3306"
    environment:
     # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
     - "TZ=CST-8"
     - "MYSQL_ROOT_PASSWORD=123456"
     - "MYSQL_ROOT_HOST=%"
     - "MYSQL_DATABASE=test"
     - "MYSQL_USER=terwer"
     - "MYSQL_PASSWORD=123456"
    volumes:
     - ./data:/var/lib/mysql
     - ./init:/docker-entrypoint-initdb.d/
     - ./sql:/opt/
     - ./mylog:/mylog/
    restart: "no"