# docker-compose --log-level INFO up --build portable-mysql57
# docker-compose --log-level INFO up

version: '3'
services:
  portable-mysql57:
    image: mysql/mysql-server:5.7.38
    container_name: portable-mysql57
    privileged: true
    ports:
      - "3306:3306"
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=terwer"
      - "MYSQL_PASSWORD=123456"
    volumes:
      - ./conf/my.cnf:/etc/my.cnf
      - ./data:/var/data
    restart: "no"